# Generated by Django 3.2.9 on 2022-03-09 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('taste', models.CharField(max_length=100)),
                ('short_content', models.CharField(max_length=50)),
                ('long_content', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_users', models.ManyToManyField(related_name='liked_travels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
