# Generated by Django 3.2.9 on 2022-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_travel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='taste',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='type',
        ),
        migrations.AddField(
            model_name='travel',
            name='address',
            field=models.CharField(default=1, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='hashtag',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
