# Generated by Django 3.2.9 on 2022-03-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_auto_20220319_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='travel',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='travel',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
