# Generated by Django 3.2.9 on 2022-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_auto_20220319_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
